### ISSUE TITLE
Escolher um dos casos de uso para implementar na SPRINT 1. Escrever os fluxos alternativos do caso de uso escolhido.

### ISSUE THREAD

**Issue by tmsasaki** [gabrielramoos/ppads-projeto-05j-2018s2#2]

**Comment by gabrielramoos** [comment]
**### Identificador	CSU02**
Nome	Consultar regiões que possuem baixa velocidade de internet

Atores	Cliente

Sumário	Consulta para mostrar os pontos onde a internet é reduzida, ficando com baixa velocidade

Complexidade	Médio

Pré-condições	N/D

Pós Condições	É mostrada as regiões que possuem baixa velocidade de internet

Pontos de Inclusão	N/D

Pontos de Extensão	N/D

Fluxo Principal

1. O cliente entra na parte de consultar região com baixa velocidade de internet.

2. O cliente faz uma consulta onde possui regiões com baixa velocidade de internet.

                 3.	O sistema busca no banco de dados quais são as regiões onde possuem uma baixa velocidade de internet.
               4.	O sistema devolve para o usuário em forma gráfica as regiões que tem baixa velocidade de internet.

Fluxo alternativo:
1. O cliente entra na parte de consultar região (UF ou Município) com baixa velocidade de internet.

2. O cliente faz uma consulta onde possui regiões (UF ou Município) com baixa velocidade de internet.

3. O sistema busca no banco de dados quais são as regiões (UF ou Município) onde possuem uma baixa velocidade de internet.

4. Na área designada, a velocidade média é acima de 35Mbps, considerada ultra banda larga.

5. O sistema devolve a informação e pergunta se o usuário quer verificar uma nova região (UF ou Município).
