### ISSUE TITLE
Implantar uma aplicação Hello World na plataforma escolhida para o projeto. Data: 04/09/2018.

### ISSUE THREAD

**Issue by tmsasaki** [gabrielramoos/ppads-projeto-05j-2018s2#3]

**Comment by gabrielramoos** [comment]
http://gustavomorozi.com.s3-website-sa-east-1.amazonaws.com

**Comment by tmsasaki** [comment]
Ok. Verificado. Se quiser, pode parar o serviço para não consumir créditos de sua conta.
